name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  simple_animations: ^4.2.0
  page_transition: ^2.0.9 #Tạo hiệu ứng chuyển trang 
  cupertino_icons: ^1.0.6
  animate_do: ^2.0.0  # Tạo animation khi show page
  provider: ^6.0.5
  flutter_slidable: ^3.1.0 # tạo ra widget sử dụng hành động trượt trên app
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  animations: ^2.0.11 # tạo các animation 
flutter:
  uses-material-design: true
  assets:
   
    - assets/images/
    

